// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjibXebh5kSGOwFSYbS6S25AhtQyz5VFU',
    appId: '1:530142180280:web:dfac9aa938a39466c8554d',
    messagingSenderId: '530142180280',
    projectId: 'first-app-4ac34',
    authDomain: 'first-app-4ac34.firebaseapp.com',
    storageBucket: 'first-app-4ac34.firebasestorage.app',
    measurementId: 'G-GFLXDW9EKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Tq3NipDB5zARvShLIeD2Q5BwcgVM7cU',
    appId: '1:530142180280:android:bf76f259aadb0e13c8554d',
    messagingSenderId: '530142180280',
    projectId: 'first-app-4ac34',
    storageBucket: 'first-app-4ac34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL_nawFUviOZPsCCyvVnnkd7gXeYo7KAI',
    appId: '1:530142180280:ios:1c3ce9bc2fbcac58c8554d',
    messagingSenderId: '530142180280',
    projectId: 'first-app-4ac34',
    storageBucket: 'first-app-4ac34.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL_nawFUviOZPsCCyvVnnkd7gXeYo7KAI',
    appId: '1:530142180280:ios:1c3ce9bc2fbcac58c8554d',
    messagingSenderId: '530142180280',
    projectId: 'first-app-4ac34',
    storageBucket: 'first-app-4ac34.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjibXebh5kSGOwFSYbS6S25AhtQyz5VFU',
    appId: '1:530142180280:web:26f93794c4c559d3c8554d',
    messagingSenderId: '530142180280',
    projectId: 'first-app-4ac34',
    authDomain: 'first-app-4ac34.firebaseapp.com',
    storageBucket: 'first-app-4ac34.firebasestorage.app',
    measurementId: 'G-CRHBKVREBK',
  );
}
